<?php

namespace ApplicationBundle\Contract;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface CentreRepositoryInterface  extends RepositoryInterface
{
}
