<?php

namespace AppBundle\Repository;

/**
 * DepartamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentRepository extends \Doctrine\ORM\EntityRepository
{
}
