<?php

namespace AppBundle\Repository;

/**
 * TipusCentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusCentreRepository extends \Doctrine\ORM\EntityRepository
{
}
