application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /

domain:
    resource: "@DomainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
