<?php

namespace AppBundle\Domain\Model\Centre;

use  \Doctrine\ORM\EntityRepository;
use  \Doctrine\ORM\EntityManager;
use  Uic\Application\Contract\CentreRepositoryInterface;
use  Uic\Application\Factory\CentreFactory;
use  AppBundle\Factory\CentreFactoryInf;
use  AppBundle\Factory\TipusCentreFactoryInf;
use  AppBundle\Adapter\Logs\LogsAdapter;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepositoryDoctrine extends \Doctrine\ORM\EntityRepository implements CentreRepositoryInterface 
{
    

}
