departaments_index:
    path:     /
    defaults: { _controller: "AppBundle:Departaments\Departaments:index" }
    methods:  GET

departaments_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Departaments\Departaments:show" }
    methods:  GET

departaments_new:
    path:     /new
    defaults: { _controller: "AppBundle:Departaments\Departaments:new" }
    methods:  [GET, POST]

departaments_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Departaments\Departaments:edit" }
    methods:  [GET, POST]

departaments_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Departaments\Departaments:delete" }
    methods:  DELETE
