<?php

namespace AppBundle\Repository\Departaments;

/**
 * DepartamentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentsRepository extends \Doctrine\ORM\EntityRepository
{
}
