<?php

namespace AppBundle\Domain\Model\TipusCentre;

use \Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\EntityManager;
use ApplicationBundle\Contract\TipusCentreRepositoryInterface;
use ApplicationBundle\Factory\TipusCentreFactory;
use DomainBundle\Entity\TipusCentre\TipusCentre;
use AppBundle\Factory\TipusCentreFactoryInf;
use AppBundle\Adapter\Logs\LogsAdapter;

/**
 * TipusCentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusCentreRepositoryDoctrine extends \Doctrine\ORM\EntityRepository implements TipusCentreRepositoryInterface
{
    
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id     The identifier.
     * @return object|NULL  The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function find($id)
    {
        $tipusCentre = parent::find($id);

        return $tipusCentre;
    }
    
    /**
     * Finds all entities in the repository.
     *
     * @return array The entities (DOMAIN).
     */
    public function findAll()
    {
        $tipusCentre = parent::findAll();
        
        return $tipusCentre;
    }

     /**
     * Finds entities by a set of criteria.
     *
     * @param array      $criteria
     * @param array|null $orderBy
     * @param int|null   $limit
     * @param int|null   $offset
     *
     * @return array The objects. (DOMAIN)
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {

        $tipusCentres = parent::findBy($criteria, $orderBy, $limit, $offset);

        return $tipusCentres;

    }

    /**
     * Finds a single entity by a set of criteria.
     *
     * @param array $criteria
     * @param array|null $orderBy
     *
     * @return object|null The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $tipusCentre = parent::findOneBy($criteria, $orderBy);

        return $tipusCentre;
    }



    public function create(TipusCentre $tipusCentre)
    {

        $em = $this->getEntityManager();

        $em->persist($tipusCentre);
        $em->flush();

        return $tipusCentre;
    }

    public function update()
    {
        $em = $this->getEntityManager();
        $em->flush();
    }

    public function delete(TipusCentre $tipusCentre)
    {
        $em = $this->getEntityManager();

        $em->remove($tipusCentre);
        $em->flush();
    }
}
