<?php

namespace AppBundle\Adapter\Repository;

use  \Doctrine\ORM\EntityRepository;
use  \Doctrine\ORM\EntityManager;
use  ApplicationBundle\Contract\TipusCentreRepositoryInterface;
use  ApplicationBundle\Factory\TipusCentreFactory;
use  AppBundle\Factory\TipusCentreFactoryInf;
use  AppBundle\Adapter\Logs\LogsAdapter;

/**
 * TipusCentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusCentreRepositoryDoctrine extends \Doctrine\ORM\EntityRepository implements TipusCentreRepositoryInterface 
{
    
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id     The identifier.
     * @return object|NULL  The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function find($id)
    {
    	$tipusCentreInf = parent::find($id);

        $tipusCentreDom = null;
        if (null !== $tipusCentreInf) {
            $tipusCentreDom = TipusCentreFactory::instance($tipusCentreInf->toArray());
        }

        return $tipusCentreDom;
    } 

	
    /**
     * Finds all entities in the repository.
     *
     * @return array The entities (DOMAIN).
     */
    public function findAll()
	{    

        $tipusCentresDom = parent::findAll();
        
        return $tipusCentresDom;
    }  

     /**
     * Finds entities by a set of criteria.
     *
     * @param array      $criteria
     * @param array|null $orderBy
     * @param int|null   $limit
     * @param int|null   $offset
     *
     * @return array The objects. (DOMAIN)
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {

        $tipusCentresInf = parent::findBy($criteria,$orderBy,$limit,$offset);

        $tipusCentresDom = array();
        foreach($tipusCentresInf as $tipusCentreInf) {
            
            $tipusCentreDom = TipusCentreFactory::instance($tipusCentreInf->toArray());
            
            $tipusCentresDom[] = $tipusCentreDom;
        }
        return $tipusCentresDom;

    }

    /**
     * Finds a single entity by a set of criteria.
     *
     * @param array $criteria
     * @param array|null $orderBy
     *
     * @return object|null The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $tipusCentreInf = parent::findOneBy($criteria,$orderBy);
        
        $tipusCentreDom = null;
        if (null !== $tipusCentreInf) {
            $tipusCentreDom = TipusCentreFactory::instance($tipusCentreInf->toArray());
        }

        return $tipusCentreDom;
    }



    public function create(array $params)
    {

        $em = $this->getEntityManager();
        //@todo Crear array per especificacions. DE moment a ma (en aplicacio???)

        $tipusCentreDom = TipusCentreFactory::create($params);
        
        $tipusCentreInf = TipusCentreFactoryInf::create($tipusCentreDom->toArray());

        $em->persist($tipusCentreInf);
        $em->flush();

        // S'activa el sistema de LOG (Rabbit)
        $logAdapter = new LogsAdapter();
        $logAdapter->writeLog('666','Hello hell!!');

        return $tipusCentreDom;
    }

    public function update(array $params)
    {
        $em = $this->getEntityManager();

        $tipusCentreDom = TipusCentreFactory::instance($params);

        $tipusCentreInf = parent::find($params['id']);

        //@todo agafar per Specification patten els
        if (null !== $tipusCentreInf) {
            $tipusCentreInf->setDescriEsp($params['descriEsp']);
            $tipusCentreInf->setDescriEng($params['descriEng']);
            $tipusCentreInf->setDescriCat($params['descriCat']);
            

            $em->flush();  

            // S'activa el sistema de LOG (Rabbit)
            $logAdapter = new LogsAdapter();
            $logAdapter->writeLog('666','Update hell to sky!!');  
        }


        
        
        return $tipusCentreDom;
    }



    public function delete($id)
    {
        $em = $this->getEntityManager();

        $tipusCentreInf = parent::find($id);

        $em->remove($tipusCentreInf);
        $em->flush();

        // S'activa el sistema de LOG (Rabbit)
        $logAdapter = new LogsAdapter();
        $logAdapter->writeLog('666','Bye hell!!');  
    }


}
