<?php

namespace UicBundle\Application\Contract;

/**
 * TipusCentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface TipusCentreRepositoryInterface  extends RepositoryInterface
{
}
