app_centre:
    resource: "@AppBundle/Resources/config/routing/centre_centre.yml"
    prefix:   /centre

app_tipuscentre:
    resource: "@AppBundle/Resources/config/routing/tipuscentre_tipuscentre.yml"
    prefix:   /tipuscentre