AppBundle\Entity\Centre:
    type: entity
    table: centros
    repositoryClass: AppBundle\Adapter\Repository\CentreRepositoryDoctrine
    id:
        id:
            type: integer
            id: true
            column: codigo
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '80'
        codi:
            type: string
            length: '5'
            column: cod_centro
    lifecycleCallbacks: {  }
