AppBundle\Entity\Centre:
    type: entity
    table: centros
    schema: hexagonal
    repositoryClass: AppBundle\Adapter\Repository\CentreRepositoryDoctrine
    id:
        id:
            type: string
            id: true
            column: uuid
    fields:
        nombre:
            type: string
            length: '80'
        codi:
            type: string
            length: '5'
            column: cod_centro
        mailCentre:
            type: string
            length: '50'
            column: mail_centre
        codiOficial:
            type: string
            length: '8'
            column: codigo_oficial

    lifecycleCallbacks: {  }
