<?php

namespace UicBundle\Infrastructure\Domain\Model\Centre;

use \Doctrine\ORM\EntityRepository;
use UicBundle\Application\Contract\CentreRepositoryInterface;
use UicBundle\Domain\Entity\Centre\Centre;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepositoryDoctrine extends EntityRepository implements CentreRepositoryInterface
{

    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id     The identifier.
     * @return object|NULL  The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function find($id)
    {
        $centre = parent::find($id);

        return $centre;
    }

    /**
     * Finds all entities in the repository.
     *
     * @return array The entities (DOMAIN).
     */
    public function findAll()
    {
        $centresDom = parent::findAll();
        
        return $centresDom;
    }

     /**
     * Finds entities by a set of criteria.
     *
     * @param array      $criteria
     * @param array|null $orderBy
     * @param int|null   $limit
     * @param int|null   $offset
     *
     * @return array The objects. (DOMAIN)
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {

        $centresInf = parent::findBy($criteria, $orderBy, $limit, $offset);

        return $centresInf;
    }

    /**
     * Finds a single entity by a set of criteria.
     *
     * @param array $criteria
     * @param array|null $orderBy
     *
     * @return object|null The entity instance or NULL if the entity can not be found. (DOMAIN)
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $centre = parent::findOneBy($criteria, $orderBy);
        
        return $centre;
    }


    /**
     * Flushes all changes to objects that have been queued up to now to the database.
     * This effectively synchronizes the in-memory state of managed objects with the
     * database.
     *
     * If an entity is explicitly passed to this method only this entity and
     * the cascade-persist semantics + scheduled inserts/removals are synchronized.
     * @param Centre $entity
     * @return Centre
     */
    public function create(Centre $entity)
    {
        $em = $this->getEntityManager();

        $em->persist($entity);
        $em->flush();

        // S'activa el sistema de LOG (Rabbit)
        // $logAdapter = new LogsAdapter();
        // $logAdapter->writeLog('666','Hello hell!!');

        return $entity;
    }

    /**
     * Flushes all changes to objects that have been queued up to now to the database.
     * This effectively synchronizes the in-memory state of managed objects with the
     * database.
     *
     * @throws \Doctrine\ORM\OptimisticLockException If a version check on an entity that
     *         makes use of optimistic locking fails.
     */
    public function update()
    {
        $em = $this->getEntityManager();

        $em->flush();

        // S'activa el sistema de LOG (Rabbit)
        // $logAdapter = new LogsAdapter();
        // $logAdapter->writeLog('666','Update hell to sky!!');
    }


    /**
     * Removes an entity instance.
     *
     * A removed entity will be removed from the database at or before transaction commit
     * or as a result of the flush operation.
     *
     * @param Centre $entity The entity instance to remove.
     *
     * @return void
     */
    public function delete(Centre $entity)
    {
        $em = $this->getEntityManager();
        $em->remove($entity);
        $em->flush();

        // S'activa el sistema de LOG (Rabbit)
        // $logAdapter = new LogsAdapter();
        // $logAdapter->writeLog('666','Bye hell!!');
    }
}
