centre_index:
    path:     /
    defaults: { _controller: "UicBundle:Centre/Centre:index" }
    methods:  GET

centre_show:
    path:     /{id}/show
    defaults: { _controller: "UicBundle:Centre/Centre:show" }
    methods:  GET

centre_new:
    path:     /new
    defaults: { _controller: "UicBundle:Centre/Centre:new" }
    methods:  [GET, POST]

centre_edit:
    path:     /{id}/edit
    defaults: { _controller: "UicBundle:Centre/Centre:edit" }
    methods:  [GET, POST]

centre_delete:
    path:     /{id}/delete
    defaults: { _controller: "UicBundle:Centre/Centre:delete" }
    methods:  DELETE
